language: python
sudo: false
cache:
  pip: true
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip install poetry
- pip install coveralls
- pip install codacy-coverage
install:
- poetry install
script:
- pytest tests
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
after_success:
- python-codacy-coverage -r coverage.xml
- coveralls
env:
  global:
    secure: x8IUUQIlfb/RYfdbMdNLy5Q2/WhRWhAmVZqhum1WPZq4DlhQh2o5ntDCavJ3j3iQ3vekYZPksgQicX0Z6NUz8wXH7+gsbgCHvhN4NdDI3sLMpXc95tzHWP5YY1XY9UDryjZjqAiz2FVnmth7Y++gsRnPk2vCzw0xTOpwYDZoA+qLsYWUMZWNZkwQS3HlpeIj1f869+htzgLy+BaeeCUXEdKJF5rxZZpqSOPNIAeribaEKYdGRTtxTu3Sf+pq5rVQ+LM/X/FwzJcGfxrS3yKZErr2tS/DclONGCx8hcY01mTH6+rCb/zYd8NHTU+ZEOI41vICPSWcaoHvajMmLOF8h+6FRYWAYt5yF+GfWVdnuEDMxB1/Czul7+oKI6yh3Uv0R5/Nlhu8gpZ2Qwr9zk9OyZd9X1cYtRTEpPiqH2mc4aylclR1/MD/nLs1bHB+K591duyyWPtUQE7BFT0gksLLT9S/mt2p8pPu7CF6ZTAViLD4yUArmjBF/acP/QfThaXuHWqGUxO2oRvcD/YYPwyGWw/I2qmvVSAAZwNkaMahN6SAb5vgu3yOMrsQt6xDN+dcoqNQNu1tno4naFUnYzxW0ozR4mCTycAvbh9BknxuE5gAj/mAn4ZP4et6nwXyYbqJbeAFdhlwxL8ttiqgwZLdXD9oxBYlptPORzQCrpS3U74=
